/home/jklymak/project/jklymak/AbHillInter/python
Traceback (most recent call last):
  File "getSlice.py", line 29, in <module>
    with xr.open_zarr(f'../reduceddata/{runname}/SliceMid.zar') as ds:
  File "/home/jklymak/venvs/AbHillInter2/lib/python3.8/site-packages/xarray/backends/zarr.py", line 666, in open_zarr
    ds = open_dataset(
  File "/home/jklymak/venvs/AbHillInter2/lib/python3.8/site-packages/xarray/backends/api.py", line 554, in open_dataset
    store = opener(filename_or_obj, **extra_kwargs, **backend_kwargs)
  File "/home/jklymak/venvs/AbHillInter2/lib/python3.8/site-packages/xarray/backends/zarr.py", line 324, in open_group
    zarr_group = zarr.open_group(store, **open_kwargs)
  File "/home/jklymak/venvs/AbHillInter2/lib/python3.8/site-packages/zarr/hierarchy.py", line 1166, in open_group
    raise GroupNotFoundError(path)
zarr.errors.GroupNotFoundError: group not found at path ''
building file list ... done

sent 51,111 bytes  received 20 bytes  1,032.95 bytes/sec
total size is 628,512,106  speedup is 12,292.19
